---
- name: Ubuntu Lab Setup
  hosts: localhost
  become: true
  vars:
    change_flags:
      #update_root: true

  tasks:
    # Install required packages
    - name: Install required packages
      apt:
        name:
          - git
          - curl
          - vim
          - htop
          - tmux
          - sshpass
          - net-tools
        state: latest
        update_cache: yes
    
    # create required user
    - name: Create required user
      user:
        name: labuser
        comment: Lab User
        shell: /bin/bash
        state: present
        password: "{{ 'labpassword' | password_hash('sha512') }}"
        update_password: on_create

    
    # Create password for the user
    - name: Set password for root
      when: change_flags.update_root | default(false)
      user:
        name: root
        password: "{{ 'rootpassword' | password_hash('sha512') }}"
        update_password: always
        
        
    # setup sudo access for the user
    - name: Setup sudo access for the user
      ansible.builtin.copy:
        dest: /etc/sudoers.d/20-labuser
        content: "labuser ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: '0440'

    # allow password ssh
    - name: Allow password authentication for SSH
      notify: restart ssh
      ansible.builtin.lineinfile:
        create: true
        state: present
        path: /etc/ssh/sshd_config.d/20-password-auth
        line: PasswordAuthentication yes
        owner: root
        group: root
        mode: '0600'
   

  
   # setup vimrc for the user
    - name: Setup vimrc for the user
      ansible.builtin.blockinfile:
        path: /home/labuser/.vimrc
        block: |
          set number
          set cuc
          set mouse-=a
        owner: labuser
        group: labuser
        mode: '0644'
        state: present
        create: true

  #restart ssh service
  handlers:
    - name: restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted