---
# tasks file for alpine-gemini-script
- name: Download Alpine Linux ISO
  loop:
    - vmlinuz-lts
    - initramfs-lts
    - modloop-lts
  ansible.builtin.get_url:
     url: "https://dl-cdn.alpinelinux.org/alpine/{{ alpine_version }}/releases/{{ alpine_arch }}/netboot/{{ item }}"
     dest: /var/www/html/{{ item }}

# Copy custom Alpine Linux image creation script to the server
- name: Create Custom Alpine Linux Image
  ansible.builtin.copy:
    src: create-alpine-packer-gemini-script.sh
    dest: /root/create-alpine-packer-gemini-script.sh
      
# Run the script to create the custom Alpine Linux image
- name: Execute Custom Alpine Linux Image Creation Script
  ansible.builtin.shell: bash /root/create-alpine-packer-gemini-script.sh
  args:
    chdir: /root
    creates: /var/www/html/alpine.apkovl.tar.gz