---
- name: DCHP and iPXE Server Setup
  hosts: DHCPiPXE
  become: true
  #todo create vars for the dhcp and ipxe configs to avoid hardcoding
  #vars_files:
  #  - vars/dhcp-vars.yaml
  #  - vars/ipxe-vars.yaml

  tasks:
    # update the apt cache and install the required packages
    - name: Install DHCP Packages
      ansible.builtin.apt: 
        update_cache: true
        name: 
          - isc-dhcp-server
          - apache2
          - tftpd-hpa
        state: present

    # enable and restart all the services
    - name: Enable and Restart DHCP, Apache2, TFTPD with default configuration
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - isc-dhcp-server
        - apache2
        - tftpd-hpa

    #Basic DHCP config setup
    - name: Configure DHCP
      notify: update DHCP configuration
      ansible.builtin.template: 
        dest: /etc/dhcp/dhcpd.conf
        src: templates/dhcpd.conf.j2
    
    #Ensure tftpd directory
    - name: Create TFTP root directory
      ansible.builtin.file:
        path: /srv/tftp
        state: directory
        mode: '755'
        owner: tftp
        group: tftp

    # Download the iPXE binary and place it in the TFTP root directory
    - name: Download iPXE binary
      loop: 
        - undionly.kpxe
        - x86_64-efi/ipxe.efi
      ansible.builtin.get_url:
        url: https://boot.ipxe.org/{{ item }}
        dest: /srv/tftp/{{ item }}
      #disabled till further notice#notify: update TFTPD configuration

    # Preparation of Webserver root for  Alpine Linux ISO for PXE Booting
    - name: Create Web Alpine Directory
      ansible.builtin.file: 
        name: /var/www/html/alpine
        state: directory
        mode: '755'
    
    # Create IPXE Boot Script
    - name: Create iPXE Boot Script
      #disabled till further notice#notify: update apache2 configuration
      ansible.builtin.template:
        dest: /var/www/html/boot.ipxe
        src: templates/boot.ipxe.j2

    # Prepare Boot images
    - name: Prepare Boot images
      block:
      ## To add more boot images, add them to the list below and create a template for them in the templates directory
      - name: Prepare Alpine Linux Image
        #Disabled#  notify: update apache2 configuration
        ansible.builtin.include_role:
          name: alpine-gemini-script

### Handlers
  handlers:
    - name : update TFTPD configuration
      ansible.builtin.service:
        name: tftpd-hpa
        state: restarted

    - name : update DHCP configuration
      ansible.builtin.service:
        name: isc-dhcp-server 
        state: restarted

    - name : update apache2 configuration
      ansible.builtin.service:
        name: apache2 
        state: restarted
