---
- name: DHCP Server Configuration
  hosts: DHCP
  become: true

  tasks:

    #sudo apt update && sudo apt install isc-dhcp-server
    - name: Install DHCP Packages
      ansible.builtin.apt: 
        name: 
          - isc-dhcp-server
          - apache2
          - tftpd-hpa
        state: present
    
    #Basic DHCP config setup
    - name: Configure DHCP
      ansible.builtin.copy: 
        dest: /etc/DHCP/dhcpd.conf
        src: dhcpd.conf.j2
    
    #sudo mkdir -p /var/lib/tftpboot.
    - name: Create TFTP root directory
      ansible.builtin.file:
        name: /srv/tftp
        state: directory
        mode: 755
        owner: tftp
        group: tftp

    # Download the iPXE binary and place it in the TFTP root directory
    - name: Download iPXE binary
      loop: 
        - undionly.kpxe
        - ipxe.efi
      ansible.builtin.get_url:
        url: https://boot.ipxe.org/{{ item }}
        dest: /srv/tftp/{{ item }}

    # Preparation of Webserver root for  Alpine Linux ISO for PXE Booting
    - name: Create Web Alpine Directory
      ansible.builtin.file: 
        name: /var/www/html/alpine
        state: directory
        mode: 755
    
    # Create IPXE Boot Script
    - name: Create iPXE Boot Script
      ansible.builtin.copy:
        dest: /var/www/html/boot.ipxe
        src: boot.ipxe.j2

    # Downloading the default Alpine Linux for PXE Booting
    - name: Download Alpine Linux ISO
      loop:
        - vmlinuz-lts
        - initramfs-lts
        - modloop-lts
      ansible.builtin.get_url:
        url: https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/x86_64/netboot/{{ item }}
        dest: /var/www/html/{{ item }}

    # Copy custom Alpine Linux image creation script to the server
    - name: Create Custom Alpine Linux Image
      ansible.builtin.copy:
        src: create-alpine-packer-gemini-script.sh
        dest: /root/create-alpine-packer-gemini-script.sh
      
    # Run the script to create the custom Alpine Linux image
    - name: Execute Custom Alpine Linux Image Creation Script
      ansible.builtin.shell: bash /root/create-alpine-packer-gemini-script.sh
      args:
        chdir: /root

    # enable and restart all the services
    - name: Enable and Restart DHCP, Apache2, TFPTD
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: restarted
      loop:
        - isc-dhcp-server
        - apache2
        - tftpd-hpa