---
- name: DHCP Server Configuration
  hosts: DHCP
  become: true

  tasks:
    #sudo apt update && sudo apt install isc-dhcp-server
    - name: Install DHCP Packages
      ansible.builtin.apt: 
        name: 
          - isc-dhcp-server
          - apache2
          - tftpd-hpa
        state: present

    # enable and restart all the services
    - name: Enable and Restart DHCP, Apache2, TFPTD with default configuration
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - isc-dhcp-server
        - apache2
        - tftpd-hpa

    #Basic DHCP config setup
    - name: Configure DHCP
      notify: update DHCP configuration
      ansible.builtin.template: 
        dest: /etc/dhcp/dhcpd.conf
        src: templates/dhcpd.conf.j2
    
    #Ensure tftpd directory
    - name: Create TFTP root directory
      ansible.builtin.file:
        name: /srv/tftp
        state: directory
        mode: 755
        owner: tftp
        group: tftp

    # Download the iPXE binary and place it in the TFTP root directory
    - name: Download iPXE binary
      loop: 
        - undionly.kpxe
        - ipxe.efi
      ansible.builtin.get_url:
        url: https://boot.ipxe.org/{{ item }}
        dest: /srv/tftp/{{ item }}
      notify: update TFPTD configuration

    # Preparation of Webserver root for  Alpine Linux ISO for PXE Booting
    - name: Create Web Alpine Directory
      ansible.builtin.file: 
        name: /var/www/html/alpine
        state: directory
        mode: 755
    
    # Create IPXE Boot Script
    - name: Create iPXE Boot Script
      ansible.builtin.template:
        dest: /var/www/html/boot.ipxe
        src: templates/boot.ipxe.j2

    # Create Alpine Linux image
    - name: Prepare Alpine Linux Image
      ansible.builtin.include_role:
        name: alpine-gemini-script

### Handlers
  handlers:
    - name : update TFPTD configuration
      ansible.builtin.service:
        name: tftpd-hpa
        state: restarted

    - name : update DHCP configuration
      ansible.builtin.service:
        name: isc-dhcp-server 
        state: restarted